### ISSUE TITLE
Automatize container hashes update

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirtci#125]
The process of update hashes when something is change at the containers is very error prone, for example changing stuff a base image means:
/test push-base
fix hashes
/test push-centos
fix hashes
/test providers
fix hashes

A possible solution would be to just point to "stable" all the providers and make a "post-merge" job that will update stable.

**Comment by qinqon** [comment]
@slintes there it is

**Comment by slintes** [comment]
Hey @qinqon, thanks for that proposal. We need more automation for this for sure!
About your suggestion: using a moving `stable` tag is not an ideal solution, because that can result in using old cached images. We would like to stick with shasums because of that.
My suggestion would be to track all shasums in 1 parsable text file, and get them from there where needed.
A postsubmit job which rebuilds and pushes all needed images sounds great. It only needs to update that shasum file as well then.
Let's use this issue to elaborate more on this.
