### ISSUE TITLE
virtctl is not working unless under kubevirt/kubevirt

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirtci#128]
I think this is a leftover from kubevirt. https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/virtctl.sh#L41 contains reference to parent directory/_out/cmd. That is fine on kubevirt/kubevirt, but failing on other projects. Any suggestion how to fix it?

**Comment by slintes** [comment]
Oh yes, good catch. But I'm afraid there is no better solution than to remove virtctl.sh, because it is directly related to kubevirt, which we don't want here. If other projects need virtctl, they need to download it from kubevirt's release page IMHO, just like they probably do with the deploy manifests. Does that make sense?

**Comment by phoracek** [comment]
@slintes yeah, I double that. In my project, I just added `wget released-virtctl`. I'm fine with dropping it.
