### ISSUE TITLE
Make snapshot with pods started

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirtci#148]
Starting of OKD4 cluster spends most time on downloading of the image (which gets cached on the system, so its fine) and waiting for pods to turn Ready:

```
19:25:04 [check-patch.hco-master.fc30.x86_64] + [[ 8 -le 3 ]]
19:25:04 [check-patch.hco-master.fc30.x86_64] + echo 'waiting for pods to come online'
```

Is there a way to make a snapshot of the cluster once all pods are deployed? It would make our CI much faster.

**Comment by phoracek** [comment]
@cynepco3hahue what do you think?

**Comment by cynepco3hahue** [comment]
@phoracek It does not really re-download all images, it's only for pods to start because after provisioning I am stopping all virtual machines to have the possibility to configure them on the runtime, so it only waiting for pods to start(all images already should be in the cluster), I do not think we can improve here something.

**Comment by phoracek** [comment]
I see, thanks for the explanation @cynepco3hahue, closing the issue then,
