### ISSUE TITLE
Podman (and RHEL 8) support

### ISSUE THREAD

**Issue by MarSik** [kubevirt/kubevirtci#149]
Is there a way to run kubevirtci on RHEL 8 with no docker?

The code of gocli seems to require Docker daemon as it calls the API. Well there is no docker anymore in RHEL 8 as it was replaced by the daemon-less podman.

**Comment by cynepco3hahue** [comment]
Currently no, maybe installing CE repo will help, we have plans to move our code to work with podman, it mostly depends on a load.
In general, we should just create an alternative that will work with https://github.com/containers/libpod/blob/master/API.md

**Comment by MarSik** [comment]
There is no CE repo for CentOS/RHEL 8 either. Docker only provides packages for CentOS 7 and Fedora.

I would say this is becoming quite urgent too. CentOS just announced the release day for version 8  (24th of Sep).

**Comment by slintes** [comment]
IIRC @fromanirh was experimenting with podman...?

**Comment by fromanirh** [comment]
> IIRC @fromanirh was experimenting with podman...?

I am! but only on spare cycles and not much ready for prime time yet

**Comment by fromanirh** [comment]
See also https://github.com/kubevirt/kubevirtci/pull/168

**Comment by fromanirh** [comment]
related issue: https://github.com/kubevirt/kubevirtci/issues/171

**Comment by dorzheh** [comment]
> There is no CE repo for CentOS/RHEL 8 either. Docker only provides packages for CentOS 7 and Fedora.
> 
> I would say this is becoming quite urgent too. CentOS just announced the release day for version 8 (24th of Sep).



> There is no CE repo for CentOS/RHEL 8 either. Docker only provides packages for CentOS 7 and Fedora.
> 
> I would say this is becoming quite urgent too. CentOS just announced the release day for version 8 (24th of Sep).

@MarSik , actually there is a CE repo. The below worked for me:
1. Remove podman/docker delivered with RHEL8: sudo dhf remove docker 
2. Add Docker CE repo: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
3. Install Docker CE: dnf install docker-ce --nobest -y
4. Start and enable: systemctl start docker && systemctl enable docker
Afterwards, i was able to spin up my cluster since /var/run/docker.sock exists
