### ISSUE TITLE
how to run on existing ocp?

### ISSUE THREAD

**Issue by debianmaster** [kubevirt/kubevirtci#36]
`kubevirtci`  seem to spin off docker containers on docker engine?  how can i make this native to  an existing openshift/k8s cluster?

**Comment by cynepco3hahue** [comment]
@debianmaster Can you please clarify what do you expect?

**Comment by rmohr** [comment]
Oh, missed that issue. So, I originally had a plan to add a `podify` command to gocli, which would create a pod definition out of the given flags, instead if directly  running the cluster. I think that that  would be the way to go. Note that you would need to be able to run privileged pods in order to use it.
